[2023-06-30T06:59:19.706+0000] {processor.py:153} INFO - Started process (PID=2882) to work on /opt/airflow/dags/task.py
[2023-06-30T06:59:19.708+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task.py for tasks to queue
[2023-06-30T06:59:19.709+0000] {logging_mixin.py:137} INFO - [2023-06-30T06:59:19.709+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task.py
[2023-06-30T06:59:19.734+0000] {logging_mixin.py:137} INFO - [2023-06-30T06:59:19.730+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task.py", line 3, in <module>
    from airflow.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.operators.snowflake'
[2023-06-30T06:59:19.735+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task.py
[2023-06-30T06:59:19.762+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task.py took 0.061 seconds
[2023-06-30T06:59:49.856+0000] {processor.py:153} INFO - Started process (PID=2929) to work on /opt/airflow/dags/task.py
[2023-06-30T06:59:49.858+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task.py for tasks to queue
[2023-06-30T06:59:49.860+0000] {logging_mixin.py:137} INFO - [2023-06-30T06:59:49.860+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task.py
[2023-06-30T06:59:49.871+0000] {logging_mixin.py:137} INFO - [2023-06-30T06:59:49.869+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task.py", line 3, in <module>
    from airflow.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.operators.snowflake'
[2023-06-30T06:59:49.872+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task.py
[2023-06-30T06:59:49.895+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task.py took 0.043 seconds
[2023-06-30T07:00:20.066+0000] {processor.py:153} INFO - Started process (PID=2962) to work on /opt/airflow/dags/task.py
[2023-06-30T07:00:20.069+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task.py for tasks to queue
[2023-06-30T07:00:20.071+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:00:20.071+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task.py
[2023-06-30T07:00:20.082+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:00:20.079+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task.py", line 3, in <module>
    from airflow.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.operators.snowflake'
[2023-06-30T07:00:20.083+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task.py
[2023-06-30T07:00:20.108+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task.py took 0.047 seconds
[2023-06-30T07:00:50.238+0000] {processor.py:153} INFO - Started process (PID=2995) to work on /opt/airflow/dags/task.py
[2023-06-30T07:00:50.240+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task.py for tasks to queue
[2023-06-30T07:00:50.243+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:00:50.243+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task.py
[2023-06-30T07:00:50.255+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:00:50.253+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task.py", line 3, in <module>
    from airflow.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.operators.snowflake'
[2023-06-30T07:00:50.257+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task.py
[2023-06-30T07:00:50.283+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task.py took 0.050 seconds
[2023-06-30T07:01:20.416+0000] {processor.py:153} INFO - Started process (PID=3042) to work on /opt/airflow/dags/task.py
[2023-06-30T07:01:20.419+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task.py for tasks to queue
[2023-06-30T07:01:20.420+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:01:20.420+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task.py
[2023-06-30T07:01:20.431+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:01:20.428+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task.py", line 3, in <module>
    from airflow.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.operators.snowflake'
[2023-06-30T07:01:20.433+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task.py
[2023-06-30T07:01:20.459+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task.py took 0.048 seconds
[2023-06-30T07:01:50.587+0000] {processor.py:153} INFO - Started process (PID=3075) to work on /opt/airflow/dags/task.py
[2023-06-30T07:01:50.589+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task.py for tasks to queue
[2023-06-30T07:01:50.591+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:01:50.591+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task.py
[2023-06-30T07:01:50.603+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:01:50.600+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task.py", line 3, in <module>
    from airflow.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.operators.snowflake'
[2023-06-30T07:01:50.604+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task.py
[2023-06-30T07:01:50.629+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task.py took 0.047 seconds
[2023-06-30T07:02:20.770+0000] {processor.py:153} INFO - Started process (PID=3122) to work on /opt/airflow/dags/task.py
[2023-06-30T07:02:20.772+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task.py for tasks to queue
[2023-06-30T07:02:20.774+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:02:20.774+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task.py
[2023-06-30T07:02:20.786+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:02:20.783+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task.py", line 3, in <module>
    from airflow.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.operators.snowflake'
[2023-06-30T07:02:20.787+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task.py
[2023-06-30T07:02:20.815+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task.py took 0.048 seconds
[2023-06-30T07:02:50.942+0000] {processor.py:153} INFO - Started process (PID=3155) to work on /opt/airflow/dags/task.py
[2023-06-30T07:02:50.946+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task.py for tasks to queue
[2023-06-30T07:02:50.948+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:02:50.948+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task.py
[2023-06-30T07:02:50.961+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:02:50.959+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task.py", line 3, in <module>
    from airflow.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.operators.snowflake'
[2023-06-30T07:02:50.963+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task.py
[2023-06-30T07:02:50.989+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task.py took 0.052 seconds
[2023-06-30T07:03:21.139+0000] {processor.py:153} INFO - Started process (PID=3197) to work on /opt/airflow/dags/task.py
[2023-06-30T07:03:21.141+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task.py for tasks to queue
[2023-06-30T07:03:21.142+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:03:21.142+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task.py
[2023-06-30T07:03:21.151+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:03:21.149+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task.py", line 3, in <module>
    from airflow.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.operators.snowflake'
[2023-06-30T07:03:21.165+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task.py
[2023-06-30T07:03:21.194+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task.py took 0.059 seconds
[2023-06-30T07:03:51.306+0000] {processor.py:153} INFO - Started process (PID=3235) to work on /opt/airflow/dags/task.py
[2023-06-30T07:03:51.309+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task.py for tasks to queue
[2023-06-30T07:03:51.311+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:03:51.311+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task.py
[2023-06-30T07:03:51.321+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:03:51.319+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task.py", line 3, in <module>
    from airflow.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.operators.snowflake'
[2023-06-30T07:03:51.323+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task.py
[2023-06-30T07:03:51.347+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task.py took 0.045 seconds
[2023-06-30T07:04:21.564+0000] {processor.py:153} INFO - Started process (PID=3268) to work on /opt/airflow/dags/task.py
[2023-06-30T07:04:21.567+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task.py for tasks to queue
[2023-06-30T07:04:21.569+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:04:21.569+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task.py
[2023-06-30T07:04:21.583+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:04:21.581+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task.py", line 3, in <module>
    from airflow.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.operators.snowflake'
[2023-06-30T07:04:21.585+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task.py
[2023-06-30T07:04:21.620+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task.py took 0.061 seconds
[2023-06-30T07:04:51.727+0000] {processor.py:153} INFO - Started process (PID=3315) to work on /opt/airflow/dags/task.py
[2023-06-30T07:04:51.729+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task.py for tasks to queue
[2023-06-30T07:04:51.732+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:04:51.731+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task.py
[2023-06-30T07:04:51.743+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:04:51.740+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task.py", line 3, in <module>
    from airflow.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.operators.snowflake'
[2023-06-30T07:04:51.745+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task.py
[2023-06-30T07:04:51.774+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task.py took 0.052 seconds
[2023-06-30T07:05:21.944+0000] {processor.py:153} INFO - Started process (PID=3348) to work on /opt/airflow/dags/task.py
[2023-06-30T07:05:21.946+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task.py for tasks to queue
[2023-06-30T07:05:21.948+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:05:21.948+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task.py
[2023-06-30T07:05:21.958+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:05:21.956+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task.py", line 3, in <module>
    from airflow.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.operators.snowflake'
[2023-06-30T07:05:21.960+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task.py
[2023-06-30T07:05:21.984+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task.py took 0.043 seconds
[2023-06-30T07:05:52.120+0000] {processor.py:153} INFO - Started process (PID=3395) to work on /opt/airflow/dags/task.py
[2023-06-30T07:05:52.123+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task.py for tasks to queue
[2023-06-30T07:05:52.125+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:05:52.125+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task.py
[2023-06-30T07:05:52.138+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:05:52.135+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task.py", line 3, in <module>
    from airflow.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.operators.snowflake'
[2023-06-30T07:05:52.140+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task.py
[2023-06-30T07:05:52.170+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task.py took 0.055 seconds
[2023-06-30T07:06:22.299+0000] {processor.py:153} INFO - Started process (PID=3428) to work on /opt/airflow/dags/task.py
[2023-06-30T07:06:22.301+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task.py for tasks to queue
[2023-06-30T07:06:22.303+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:06:22.303+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task.py
[2023-06-30T07:06:22.314+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:06:22.311+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task.py", line 3, in <module>
    from airflow.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.operators.snowflake'
[2023-06-30T07:06:22.316+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task.py
[2023-06-30T07:06:22.342+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task.py took 0.048 seconds
[2023-06-30T07:06:52.500+0000] {processor.py:153} INFO - Started process (PID=3470) to work on /opt/airflow/dags/task.py
[2023-06-30T07:06:52.501+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task.py for tasks to queue
[2023-06-30T07:06:52.503+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:06:52.503+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task.py
[2023-06-30T07:06:52.512+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:06:52.510+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task.py", line 3, in <module>
    from airflow.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.operators.snowflake'
[2023-06-30T07:06:52.514+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task.py
[2023-06-30T07:06:52.539+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task.py took 0.043 seconds
[2023-06-30T07:07:22.664+0000] {processor.py:153} INFO - Started process (PID=3508) to work on /opt/airflow/dags/task.py
[2023-06-30T07:07:22.666+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task.py for tasks to queue
[2023-06-30T07:07:22.668+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:07:22.668+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task.py
[2023-06-30T07:07:22.679+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:07:22.676+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task.py", line 3, in <module>
    from airflow.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.operators.snowflake'
[2023-06-30T07:07:22.680+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task.py
[2023-06-30T07:07:22.706+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task.py took 0.046 seconds
[2023-06-30T07:07:52.862+0000] {processor.py:153} INFO - Started process (PID=3541) to work on /opt/airflow/dags/task.py
[2023-06-30T07:07:52.879+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task.py for tasks to queue
[2023-06-30T07:07:52.881+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:07:52.881+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task.py
[2023-06-30T07:07:52.891+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:07:52.889+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task.py", line 3, in <module>
    from airflow.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.operators.snowflake'
[2023-06-30T07:07:52.893+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task.py
[2023-06-30T07:07:52.917+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task.py took 0.059 seconds
[2023-06-30T07:08:23.039+0000] {processor.py:153} INFO - Started process (PID=3588) to work on /opt/airflow/dags/task.py
[2023-06-30T07:08:23.041+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task.py for tasks to queue
[2023-06-30T07:08:23.042+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:08:23.042+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task.py
[2023-06-30T07:08:23.053+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:08:23.051+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task.py", line 3, in <module>
    from airflow.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.operators.snowflake'
[2023-06-30T07:08:23.055+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task.py
[2023-06-30T07:08:23.108+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task.py took 0.075 seconds
[2023-06-30T07:08:53.242+0000] {processor.py:153} INFO - Started process (PID=3621) to work on /opt/airflow/dags/task.py
[2023-06-30T07:08:53.244+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task.py for tasks to queue
[2023-06-30T07:08:53.246+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:08:53.245+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task.py
[2023-06-30T07:08:53.256+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:08:53.254+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task.py", line 3, in <module>
    from airflow.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.operators.snowflake'
[2023-06-30T07:08:53.259+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task.py
[2023-06-30T07:08:53.286+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task.py took 0.049 seconds
[2023-06-30T07:09:23.494+0000] {processor.py:153} INFO - Started process (PID=3668) to work on /opt/airflow/dags/task.py
[2023-06-30T07:09:23.496+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task.py for tasks to queue
[2023-06-30T07:09:23.497+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:09:23.497+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task.py
[2023-06-30T07:09:23.507+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:09:23.505+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task.py", line 3, in <module>
    from airflow.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.operators.snowflake'
[2023-06-30T07:09:23.508+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task.py
[2023-06-30T07:09:23.532+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task.py took 0.041 seconds
[2023-06-30T07:09:53.653+0000] {processor.py:153} INFO - Started process (PID=3701) to work on /opt/airflow/dags/task.py
[2023-06-30T07:09:53.655+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task.py for tasks to queue
[2023-06-30T07:09:53.657+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:09:53.657+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task.py
[2023-06-30T07:09:53.668+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:09:53.665+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task.py", line 3, in <module>
    from airflow.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.operators.snowflake'
[2023-06-30T07:09:53.669+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task.py
[2023-06-30T07:09:53.693+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task.py took 0.046 seconds
[2023-06-30T07:10:23.851+0000] {processor.py:153} INFO - Started process (PID=3743) to work on /opt/airflow/dags/task.py
[2023-06-30T07:10:23.854+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task.py for tasks to queue
[2023-06-30T07:10:23.855+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:10:23.855+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task.py
[2023-06-30T07:10:23.869+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:10:23.866+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task.py", line 3, in <module>
    from airflow.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.operators.snowflake'
[2023-06-30T07:10:23.871+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task.py
[2023-06-30T07:10:23.899+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task.py took 0.052 seconds
[2023-06-30T07:10:54.026+0000] {processor.py:153} INFO - Started process (PID=3781) to work on /opt/airflow/dags/task.py
[2023-06-30T07:10:54.029+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task.py for tasks to queue
[2023-06-30T07:10:54.031+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:10:54.031+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task.py
[2023-06-30T07:10:54.043+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:10:54.041+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task.py", line 3, in <module>
    from airflow.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.operators.snowflake'
[2023-06-30T07:10:54.045+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task.py
[2023-06-30T07:10:54.071+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task.py took 0.050 seconds
[2023-06-30T07:11:24.229+0000] {processor.py:153} INFO - Started process (PID=3814) to work on /opt/airflow/dags/task.py
[2023-06-30T07:11:24.231+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task.py for tasks to queue
[2023-06-30T07:11:24.233+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:11:24.233+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task.py
[2023-06-30T07:11:24.243+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:11:24.240+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task.py", line 3, in <module>
    from airflow.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.operators.snowflake'
[2023-06-30T07:11:24.244+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task.py
[2023-06-30T07:11:24.269+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task.py took 0.044 seconds
[2023-06-30T07:11:54.402+0000] {processor.py:153} INFO - Started process (PID=3861) to work on /opt/airflow/dags/task.py
[2023-06-30T07:11:54.405+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task.py for tasks to queue
[2023-06-30T07:11:54.407+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:11:54.407+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task.py
[2023-06-30T07:11:54.415+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:11:54.413+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task.py", line 3, in <module>
    from airflow.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.operators.snowflake'
[2023-06-30T07:11:54.416+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task.py
[2023-06-30T07:11:54.438+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task.py took 0.039 seconds
[2023-06-30T07:12:24.597+0000] {processor.py:153} INFO - Started process (PID=3894) to work on /opt/airflow/dags/task.py
[2023-06-30T07:12:24.600+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task.py for tasks to queue
[2023-06-30T07:12:24.602+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:12:24.602+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task.py
[2023-06-30T07:12:24.615+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:12:24.612+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task.py", line 3, in <module>
    from airflow.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.operators.snowflake'
[2023-06-30T07:12:24.617+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task.py
[2023-06-30T07:12:24.645+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task.py took 0.054 seconds
[2023-06-30T07:12:54.761+0000] {processor.py:153} INFO - Started process (PID=3942) to work on /opt/airflow/dags/task.py
[2023-06-30T07:12:54.764+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task.py for tasks to queue
[2023-06-30T07:12:54.766+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:12:54.766+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task.py
[2023-06-30T07:12:54.781+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:12:54.778+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task.py", line 3, in <module>
    from airflow.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.operators.snowflake'
[2023-06-30T07:12:54.783+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task.py
[2023-06-30T07:12:54.810+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task.py took 0.055 seconds
[2023-06-30T07:13:24.945+0000] {processor.py:153} INFO - Started process (PID=3975) to work on /opt/airflow/dags/task.py
[2023-06-30T07:13:24.948+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task.py for tasks to queue
[2023-06-30T07:13:24.950+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:13:24.950+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task.py
[2023-06-30T07:13:24.964+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:13:24.961+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task.py", line 3, in <module>
    from airflow.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.operators.snowflake'
[2023-06-30T07:13:24.966+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task.py
[2023-06-30T07:13:24.994+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task.py took 0.053 seconds
[2023-06-30T07:13:55.115+0000] {processor.py:153} INFO - Started process (PID=4022) to work on /opt/airflow/dags/task.py
[2023-06-30T07:13:55.117+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task.py for tasks to queue
[2023-06-30T07:13:55.119+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:13:55.119+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task.py
[2023-06-30T07:13:55.131+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:13:55.128+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task.py", line 3, in <module>
    from airflow.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.operators.snowflake'
[2023-06-30T07:13:55.132+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task.py
[2023-06-30T07:13:55.153+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task.py took 0.043 seconds
[2023-06-30T07:14:25.344+0000] {processor.py:153} INFO - Started process (PID=4055) to work on /opt/airflow/dags/task.py
[2023-06-30T07:14:25.347+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task.py for tasks to queue
[2023-06-30T07:14:25.348+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:14:25.348+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task.py
[2023-06-30T07:14:25.360+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:14:25.357+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task.py", line 3, in <module>
    from airflow.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.operators.snowflake'
[2023-06-30T07:14:25.361+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task.py
[2023-06-30T07:14:25.387+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task.py took 0.047 seconds
[2023-06-30T07:14:55.523+0000] {processor.py:153} INFO - Started process (PID=4097) to work on /opt/airflow/dags/task.py
[2023-06-30T07:14:55.525+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task.py for tasks to queue
[2023-06-30T07:14:55.527+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:14:55.527+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task.py
[2023-06-30T07:14:55.535+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:14:55.533+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task.py", line 3, in <module>
    from airflow.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.operators.snowflake'
[2023-06-30T07:14:55.537+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task.py
[2023-06-30T07:14:55.558+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task.py took 0.038 seconds
[2023-06-30T07:15:25.710+0000] {processor.py:153} INFO - Started process (PID=4135) to work on /opt/airflow/dags/task.py
[2023-06-30T07:15:25.712+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task.py for tasks to queue
[2023-06-30T07:15:25.714+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:15:25.714+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task.py
[2023-06-30T07:15:25.725+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:15:25.722+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task.py", line 3, in <module>
    from airflow.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.operators.snowflake'
[2023-06-30T07:15:25.726+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task.py
[2023-06-30T07:15:25.751+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task.py took 0.045 seconds
[2023-06-30T07:15:55.909+0000] {processor.py:153} INFO - Started process (PID=4168) to work on /opt/airflow/dags/task.py
[2023-06-30T07:15:55.911+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task.py for tasks to queue
[2023-06-30T07:15:55.913+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:15:55.913+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task.py
[2023-06-30T07:15:55.923+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:15:55.921+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task.py", line 3, in <module>
    from airflow.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.operators.snowflake'
[2023-06-30T07:15:55.925+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task.py
[2023-06-30T07:15:55.950+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task.py took 0.046 seconds
[2023-06-30T07:16:26.084+0000] {processor.py:153} INFO - Started process (PID=4215) to work on /opt/airflow/dags/task.py
[2023-06-30T07:16:26.087+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task.py for tasks to queue
[2023-06-30T07:16:26.089+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:16:26.089+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task.py
[2023-06-30T07:16:26.103+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:16:26.100+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task.py", line 3, in <module>
    from airflow.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.operators.snowflake'
[2023-06-30T07:16:26.106+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task.py
[2023-06-30T07:16:26.133+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task.py took 0.054 seconds
[2023-06-30T07:16:56.282+0000] {processor.py:153} INFO - Started process (PID=4248) to work on /opt/airflow/dags/task.py
[2023-06-30T07:16:56.284+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task.py for tasks to queue
[2023-06-30T07:16:56.286+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:16:56.286+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task.py
[2023-06-30T07:16:56.298+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:16:56.295+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task.py", line 3, in <module>
    from airflow.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.operators.snowflake'
[2023-06-30T07:16:56.300+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task.py
[2023-06-30T07:16:56.326+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task.py took 0.048 seconds
[2023-06-30T07:17:26.464+0000] {processor.py:153} INFO - Started process (PID=4295) to work on /opt/airflow/dags/task.py
[2023-06-30T07:17:26.466+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task.py for tasks to queue
[2023-06-30T07:17:26.468+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:17:26.468+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task.py
[2023-06-30T07:17:26.479+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:17:26.477+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task.py", line 3, in <module>
    from airflow.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.operators.snowflake'
[2023-06-30T07:17:26.480+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task.py
[2023-06-30T07:17:26.504+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task.py took 0.046 seconds
[2023-06-30T07:17:56.641+0000] {processor.py:153} INFO - Started process (PID=4328) to work on /opt/airflow/dags/task.py
[2023-06-30T07:17:56.643+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task.py for tasks to queue
[2023-06-30T07:17:56.645+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:17:56.645+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task.py
[2023-06-30T07:17:56.656+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:17:56.653+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task.py", line 3, in <module>
    from airflow.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.operators.snowflake'
[2023-06-30T07:17:56.658+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task.py
[2023-06-30T07:17:56.683+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task.py took 0.047 seconds
[2023-06-30T07:18:26.814+0000] {processor.py:153} INFO - Started process (PID=4370) to work on /opt/airflow/dags/task.py
[2023-06-30T07:18:26.816+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task.py for tasks to queue
[2023-06-30T07:18:26.818+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:18:26.818+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task.py
[2023-06-30T07:18:26.827+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:18:26.824+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task.py", line 3, in <module>
    from airflow.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.operators.snowflake'
[2023-06-30T07:18:26.828+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task.py
[2023-06-30T07:18:26.850+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task.py took 0.040 seconds
[2023-06-30T07:18:57.011+0000] {processor.py:153} INFO - Started process (PID=4408) to work on /opt/airflow/dags/task.py
[2023-06-30T07:18:57.013+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task.py for tasks to queue
[2023-06-30T07:18:57.015+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:18:57.015+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task.py
[2023-06-30T07:18:57.024+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:18:57.022+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task.py", line 3, in <module>
    from airflow.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.operators.snowflake'
[2023-06-30T07:18:57.025+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task.py
[2023-06-30T07:18:57.045+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task.py took 0.038 seconds
[2023-06-30T07:19:27.230+0000] {processor.py:153} INFO - Started process (PID=4441) to work on /opt/airflow/dags/task.py
[2023-06-30T07:19:27.233+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task.py for tasks to queue
[2023-06-30T07:19:27.235+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:19:27.234+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task.py
[2023-06-30T07:19:27.246+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:19:27.244+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task.py", line 3, in <module>
    from airflow.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.operators.snowflake'
[2023-06-30T07:19:27.248+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task.py
[2023-06-30T07:19:27.271+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task.py took 0.045 seconds
[2023-06-30T07:19:57.411+0000] {processor.py:153} INFO - Started process (PID=4488) to work on /opt/airflow/dags/task.py
[2023-06-30T07:19:57.414+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task.py for tasks to queue
[2023-06-30T07:19:57.416+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:19:57.416+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task.py
[2023-06-30T07:19:57.432+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:19:57.429+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task.py", line 3, in <module>
    from airflow.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.operators.snowflake'
[2023-06-30T07:19:57.434+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task.py
[2023-06-30T07:19:57.474+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task.py took 0.070 seconds
[2023-06-30T07:20:27.619+0000] {processor.py:153} INFO - Started process (PID=4520) to work on /opt/airflow/dags/task.py
[2023-06-30T07:20:27.622+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task.py for tasks to queue
[2023-06-30T07:20:27.624+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:20:27.624+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task.py
[2023-06-30T07:20:27.635+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:20:27.632+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task.py", line 3, in <module>
    from airflow.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.operators.snowflake'
[2023-06-30T07:20:27.636+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task.py
[2023-06-30T07:20:27.664+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task.py took 0.049 seconds
[2023-06-30T07:20:57.841+0000] {processor.py:153} INFO - Started process (PID=4567) to work on /opt/airflow/dags/task.py
[2023-06-30T07:20:57.844+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task.py for tasks to queue
[2023-06-30T07:20:57.846+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:20:57.846+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task.py
[2023-06-30T07:20:57.859+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:20:57.855+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task.py", line 3, in <module>
    from airflow.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.operators.snowflake'
[2023-06-30T07:20:57.860+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task.py
[2023-06-30T07:20:57.899+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task.py took 0.062 seconds
[2023-06-30T07:21:27.996+0000] {processor.py:153} INFO - Started process (PID=4600) to work on /opt/airflow/dags/task.py
[2023-06-30T07:21:27.998+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task.py for tasks to queue
[2023-06-30T07:21:28.000+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:21:28.000+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task.py
[2023-06-30T07:21:28.015+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:21:28.012+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task.py", line 3, in <module>
    from airflow.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.operators.snowflake'
[2023-06-30T07:21:28.016+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task.py
[2023-06-30T07:21:28.048+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task.py took 0.057 seconds
[2023-06-30T07:21:58.220+0000] {processor.py:153} INFO - Started process (PID=4633) to work on /opt/airflow/dags/task.py
[2023-06-30T07:21:58.223+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task.py for tasks to queue
[2023-06-30T07:21:58.225+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:21:58.225+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task.py
[2023-06-30T07:21:58.237+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:21:58.234+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task.py", line 3, in <module>
    from airflow.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.operators.snowflake'
[2023-06-30T07:21:58.238+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task.py
[2023-06-30T07:21:58.268+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task.py took 0.052 seconds
[2023-06-30T07:22:28.400+0000] {processor.py:153} INFO - Started process (PID=4680) to work on /opt/airflow/dags/task.py
[2023-06-30T07:22:28.404+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task.py for tasks to queue
[2023-06-30T07:22:28.406+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:22:28.406+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task.py
[2023-06-30T07:22:28.419+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:22:28.416+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task.py", line 3, in <module>
    from airflow.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.operators.snowflake'
[2023-06-30T07:22:28.420+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task.py
[2023-06-30T07:22:28.450+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task.py took 0.055 seconds
[2023-06-30T07:22:58.604+0000] {processor.py:153} INFO - Started process (PID=4713) to work on /opt/airflow/dags/task.py
[2023-06-30T07:22:58.609+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task.py for tasks to queue
[2023-06-30T07:22:58.611+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:22:58.611+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task.py
[2023-06-30T07:22:58.624+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:22:58.621+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task.py", line 3, in <module>
    from airflow.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.operators.snowflake'
[2023-06-30T07:22:58.626+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task.py
[2023-06-30T07:22:58.657+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task.py took 0.057 seconds
[2023-06-30T07:23:28.777+0000] {processor.py:153} INFO - Started process (PID=4754) to work on /opt/airflow/dags/task.py
[2023-06-30T07:23:28.779+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task.py for tasks to queue
[2023-06-30T07:23:28.781+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:23:28.780+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task.py
[2023-06-30T07:23:28.789+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:23:28.787+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task.py", line 3, in <module>
    from airflow.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.operators.snowflake'
[2023-06-30T07:23:28.791+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task.py
[2023-06-30T07:23:28.817+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task.py took 0.044 seconds
[2023-06-30T07:23:59.001+0000] {processor.py:153} INFO - Started process (PID=4794) to work on /opt/airflow/dags/task.py
[2023-06-30T07:23:59.004+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task.py for tasks to queue
[2023-06-30T07:23:59.006+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:23:59.006+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task.py
[2023-06-30T07:23:59.017+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:23:59.014+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task.py", line 3, in <module>
    from airflow.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.operators.snowflake'
[2023-06-30T07:23:59.018+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task.py
[2023-06-30T07:23:59.042+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task.py took 0.045 seconds
[2023-06-30T07:24:29.164+0000] {processor.py:153} INFO - Started process (PID=4827) to work on /opt/airflow/dags/task.py
[2023-06-30T07:24:29.166+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task.py for tasks to queue
[2023-06-30T07:24:29.168+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:24:29.168+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task.py
[2023-06-30T07:24:29.177+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:24:29.175+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task.py", line 3, in <module>
    from airflow.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.operators.snowflake'
[2023-06-30T07:24:29.178+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task.py
[2023-06-30T07:24:29.199+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task.py took 0.040 seconds
[2023-06-30T07:24:59.395+0000] {processor.py:153} INFO - Started process (PID=4874) to work on /opt/airflow/dags/task.py
[2023-06-30T07:24:59.397+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task.py for tasks to queue
[2023-06-30T07:24:59.399+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:24:59.398+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task.py
[2023-06-30T07:24:59.408+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:24:59.406+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task.py", line 3, in <module>
    from airflow.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.operators.snowflake'
[2023-06-30T07:24:59.410+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task.py
[2023-06-30T07:24:59.435+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task.py took 0.045 seconds
[2023-06-30T07:25:29.583+0000] {processor.py:153} INFO - Started process (PID=4907) to work on /opt/airflow/dags/task.py
[2023-06-30T07:25:29.585+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task.py for tasks to queue
[2023-06-30T07:25:29.587+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:25:29.587+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task.py
[2023-06-30T07:25:29.599+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:25:29.596+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task.py", line 3, in <module>
    from airflow.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.operators.snowflake'
[2023-06-30T07:25:29.600+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task.py
[2023-06-30T07:25:29.624+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task.py took 0.046 seconds
[2023-06-30T07:25:59.804+0000] {processor.py:153} INFO - Started process (PID=4954) to work on /opt/airflow/dags/task.py
[2023-06-30T07:25:59.806+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task.py for tasks to queue
[2023-06-30T07:25:59.818+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:25:59.817+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task.py
[2023-06-30T07:25:59.834+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:25:59.831+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task.py", line 3, in <module>
    from airflow.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.operators.snowflake'
[2023-06-30T07:25:59.836+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task.py
[2023-06-30T07:25:59.865+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task.py took 0.066 seconds
[2023-06-30T07:26:29.965+0000] {processor.py:153} INFO - Started process (PID=4987) to work on /opt/airflow/dags/task.py
[2023-06-30T07:26:29.967+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task.py for tasks to queue
[2023-06-30T07:26:29.968+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:26:29.968+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task.py
[2023-06-30T07:26:29.979+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:26:29.976+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task.py", line 3, in <module>
    from airflow.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.operators.snowflake'
[2023-06-30T07:26:29.980+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task.py
[2023-06-30T07:26:30.002+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task.py took 0.041 seconds
[2023-06-30T07:27:00.202+0000] {processor.py:153} INFO - Started process (PID=5020) to work on /opt/airflow/dags/task.py
[2023-06-30T07:27:00.205+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task.py for tasks to queue
[2023-06-30T07:27:00.206+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:27:00.206+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task.py
[2023-06-30T07:27:00.215+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:27:00.212+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task.py", line 3, in <module>
    from airflow.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.operators.snowflake'
[2023-06-30T07:27:00.216+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task.py
[2023-06-30T07:27:00.237+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task.py took 0.038 seconds
[2023-06-30T07:27:08.260+0000] {processor.py:153} INFO - Started process (PID=5039) to work on /opt/airflow/dags/task.py
[2023-06-30T07:27:08.262+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task.py for tasks to queue
[2023-06-30T07:27:08.264+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:27:08.264+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task.py
[2023-06-30T07:27:08.287+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:27:08.284+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task.py", line 4, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-06-30T07:27:08.290+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task.py
[2023-06-30T07:27:08.317+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task.py took 0.062 seconds
[2023-06-30T07:27:38.464+0000] {processor.py:153} INFO - Started process (PID=5079) to work on /opt/airflow/dags/task.py
[2023-06-30T07:27:38.467+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task.py for tasks to queue
[2023-06-30T07:27:38.470+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:27:38.469+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task.py
[2023-06-30T07:27:38.484+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:27:38.480+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task.py", line 4, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-06-30T07:27:38.486+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task.py
[2023-06-30T07:27:38.519+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task.py took 0.058 seconds
[2023-06-30T07:28:08.640+0000] {processor.py:153} INFO - Started process (PID=5119) to work on /opt/airflow/dags/task.py
[2023-06-30T07:28:08.643+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task.py for tasks to queue
[2023-06-30T07:28:08.644+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:28:08.644+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task.py
[2023-06-30T07:28:08.656+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:28:08.654+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task.py", line 4, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-06-30T07:28:08.658+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task.py
[2023-06-30T07:28:08.684+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task.py took 0.049 seconds
[2023-06-30T07:28:38.838+0000] {processor.py:153} INFO - Started process (PID=5152) to work on /opt/airflow/dags/task.py
[2023-06-30T07:28:38.840+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task.py for tasks to queue
[2023-06-30T07:28:38.842+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:28:38.842+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task.py
[2023-06-30T07:28:38.852+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:28:38.849+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task.py", line 4, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-06-30T07:28:38.855+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task.py
[2023-06-30T07:28:38.881+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task.py took 0.047 seconds
[2023-06-30T07:29:09.008+0000] {processor.py:153} INFO - Started process (PID=5201) to work on /opt/airflow/dags/task.py
[2023-06-30T07:29:09.010+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task.py for tasks to queue
[2023-06-30T07:29:09.011+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:29:09.011+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task.py
[2023-06-30T07:29:09.022+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:29:09.019+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task.py", line 4, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-06-30T07:29:09.023+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task.py
[2023-06-30T07:29:09.050+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task.py took 0.047 seconds
[2023-06-30T07:29:39.237+0000] {processor.py:153} INFO - Started process (PID=5234) to work on /opt/airflow/dags/task.py
[2023-06-30T07:29:39.239+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task.py for tasks to queue
[2023-06-30T07:29:39.240+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:29:39.240+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task.py
[2023-06-30T07:29:39.249+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:29:39.247+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task.py", line 4, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-06-30T07:29:39.251+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task.py
[2023-06-30T07:29:39.273+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task.py took 0.040 seconds
[2023-06-30T07:30:09.412+0000] {processor.py:153} INFO - Started process (PID=5267) to work on /opt/airflow/dags/task.py
[2023-06-30T07:30:09.415+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task.py for tasks to queue
[2023-06-30T07:30:09.417+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:30:09.417+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task.py
[2023-06-30T07:30:09.430+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:30:09.427+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task.py", line 4, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-06-30T07:30:09.433+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task.py
[2023-06-30T07:30:09.461+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task.py took 0.055 seconds
[2023-06-30T07:30:39.602+0000] {processor.py:153} INFO - Started process (PID=5315) to work on /opt/airflow/dags/task.py
[2023-06-30T07:30:39.604+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task.py for tasks to queue
[2023-06-30T07:30:39.606+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:30:39.605+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task.py
[2023-06-30T07:30:39.622+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:30:39.618+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task.py", line 4, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-06-30T07:30:39.623+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task.py
[2023-06-30T07:30:39.655+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task.py took 0.058 seconds
[2023-06-30T07:31:09.784+0000] {processor.py:153} INFO - Started process (PID=5348) to work on /opt/airflow/dags/task.py
[2023-06-30T07:31:09.787+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task.py for tasks to queue
[2023-06-30T07:31:09.789+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:31:09.789+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task.py
[2023-06-30T07:31:09.800+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:31:09.798+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task.py", line 4, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-06-30T07:31:09.802+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task.py
[2023-06-30T07:31:09.831+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task.py took 0.052 seconds
[2023-06-30T07:31:39.993+0000] {processor.py:153} INFO - Started process (PID=5390) to work on /opt/airflow/dags/task.py
[2023-06-30T07:31:39.995+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task.py for tasks to queue
[2023-06-30T07:31:39.997+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:31:39.997+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task.py
[2023-06-30T07:31:40.007+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:31:40.005+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task.py", line 4, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-06-30T07:31:40.009+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task.py
[2023-06-30T07:31:40.035+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task.py took 0.046 seconds
[2023-06-30T07:32:10.166+0000] {processor.py:153} INFO - Started process (PID=5428) to work on /opt/airflow/dags/task.py
[2023-06-30T07:32:10.168+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task.py for tasks to queue
[2023-06-30T07:32:10.170+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:32:10.170+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task.py
[2023-06-30T07:32:10.186+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:32:10.183+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task.py", line 4, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-06-30T07:32:10.188+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task.py
[2023-06-30T07:32:10.219+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task.py took 0.058 seconds
[2023-06-30T07:32:20.261+0000] {processor.py:153} INFO - Started process (PID=5447) to work on /opt/airflow/dags/task.py
[2023-06-30T07:32:20.264+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task.py for tasks to queue
[2023-06-30T07:32:20.266+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:32:20.265+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task.py
[2023-06-30T07:32:20.286+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:32:20.282+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task.py", line 4, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-06-30T07:32:20.287+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task.py
[2023-06-30T07:32:20.311+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task.py took 0.054 seconds
[2023-06-30T07:32:50.461+0000] {processor.py:153} INFO - Started process (PID=5480) to work on /opt/airflow/dags/task.py
[2023-06-30T07:32:50.464+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task.py for tasks to queue
[2023-06-30T07:32:50.466+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:32:50.465+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task.py
[2023-06-30T07:32:50.479+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:32:50.476+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task.py", line 4, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-06-30T07:32:50.481+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task.py
[2023-06-30T07:32:50.510+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task.py took 0.053 seconds
[2023-06-30T07:32:55.500+0000] {processor.py:153} INFO - Started process (PID=5494) to work on /opt/airflow/dags/task.py
[2023-06-30T07:32:55.502+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task.py for tasks to queue
[2023-06-30T07:32:55.504+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:32:55.503+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task.py
[2023-06-30T07:32:55.522+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:32:55.519+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task.py", line 4, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-06-30T07:32:55.523+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task.py
[2023-06-30T07:32:55.544+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task.py took 0.048 seconds
[2023-06-30T07:33:25.743+0000] {processor.py:153} INFO - Started process (PID=5533) to work on /opt/airflow/dags/task.py
[2023-06-30T07:33:25.745+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task.py for tasks to queue
[2023-06-30T07:33:25.747+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:33:25.747+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task.py
[2023-06-30T07:33:25.760+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:33:25.757+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task.py", line 4, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-06-30T07:33:25.761+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task.py
[2023-06-30T07:33:25.786+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task.py took 0.048 seconds
[2023-06-30T07:33:55.918+0000] {processor.py:153} INFO - Started process (PID=5566) to work on /opt/airflow/dags/task.py
[2023-06-30T07:33:55.921+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task.py for tasks to queue
[2023-06-30T07:33:55.923+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:33:55.923+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task.py
[2023-06-30T07:33:55.935+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:33:55.932+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task.py", line 4, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-06-30T07:33:55.937+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task.py
[2023-06-30T07:33:55.966+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task.py took 0.053 seconds
[2023-06-30T07:34:26.147+0000] {processor.py:153} INFO - Started process (PID=5613) to work on /opt/airflow/dags/task.py
[2023-06-30T07:34:26.149+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task.py for tasks to queue
[2023-06-30T07:34:26.151+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:34:26.150+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task.py
[2023-06-30T07:34:26.161+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:34:26.158+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task.py", line 4, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-06-30T07:34:26.162+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task.py
[2023-06-30T07:34:26.187+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task.py took 0.045 seconds
[2023-06-30T07:34:56.324+0000] {processor.py:153} INFO - Started process (PID=5646) to work on /opt/airflow/dags/task.py
[2023-06-30T07:34:56.327+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task.py for tasks to queue
[2023-06-30T07:34:56.329+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:34:56.328+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task.py
[2023-06-30T07:34:56.339+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:34:56.337+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task.py", line 4, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-06-30T07:34:56.341+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task.py
[2023-06-30T07:34:56.366+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task.py took 0.046 seconds
[2023-06-30T07:35:26.514+0000] {processor.py:153} INFO - Started process (PID=5693) to work on /opt/airflow/dags/task.py
[2023-06-30T07:35:26.515+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task.py for tasks to queue
[2023-06-30T07:35:26.517+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:35:26.517+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task.py
[2023-06-30T07:35:26.527+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:35:26.524+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task.py", line 4, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-06-30T07:35:26.528+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task.py
[2023-06-30T07:35:26.553+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task.py took 0.044 seconds
[2023-06-30T07:35:56.703+0000] {processor.py:153} INFO - Started process (PID=5726) to work on /opt/airflow/dags/task.py
[2023-06-30T07:35:56.705+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task.py for tasks to queue
[2023-06-30T07:35:56.707+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:35:56.707+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task.py
[2023-06-30T07:35:56.718+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:35:56.715+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task.py", line 4, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-06-30T07:35:56.720+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task.py
[2023-06-30T07:35:56.749+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task.py took 0.051 seconds
[2023-06-30T07:36:01.755+0000] {processor.py:153} INFO - Started process (PID=5745) to work on /opt/airflow/dags/task.py
[2023-06-30T07:36:01.757+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/task.py for tasks to queue
[2023-06-30T07:36:01.760+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:36:01.759+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task.py
[2023-06-30T07:36:01.783+0000] {logging_mixin.py:137} INFO - [2023-06-30T07:36:01.780+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/task.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task.py", line 4, in <module>
    from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.snowflake'
[2023-06-30T07:36:01.785+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/task.py
[2023-06-30T07:36:01.814+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/task.py took 0.064 seconds
